### ISSUE TITLE
exception 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [senderle/topic-modeling-tool#2]
```

<200> LL/token: -8,42566

Total time: 0 seconds
java.lang.IndexOutOfBoundsException: Index: 302, Size: 10
	at java.util.ArrayList.RangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at cc.mallet.topics.gui.HtmlBuilder.buildHtml2(HtmlBuilder.java:194)
	at cc.mallet.topics.gui.HtmlBuilder.createHtmlFiles(HtmlBuilder.java:293)
	at cc.mallet.topics.gui.TopicModelingTool$TrainButtonListener.outputCsvFiles(TopicModelingTool.java:629)
	at cc.mallet.topics.gui.TopicModelingTool$TrainButtonListener.runMallet(TopicModelingTool.java:581)
	at cc.mallet.topics.gui.TopicModelingTool$TrainButtonListener$1.run(TopicModelingTool.java:446)
Mallet Output files written in C:\Users\fr\Desktop ---> 
C:\Users\fr\Desktop\output_state.gz , C:\Users\fr\Desktop\output_topic_keys

Csv Output files written in C:\Users\fr\Desktop\output_csv
Html Output files written in C:\Users\fr\Desktop\output_html

```

Original issue reported on code.google.com by `gheg.ja...@gmail.com` on 25 Nov 2011 at 4:07

**Comment by senderle** [comment]
Until the original poster returns and explains how to reproduce this, I'm closing.
