### ISSUE TITLE
Too many files open

### ISSUE THREAD

**Issue by senderle** [senderle/topic-modeling-tool#57]
At times, I see the following error: 

```
java.nio.file.FileSystemException: /Users/enderlej/Desktop/Topic Modeling/output/output_html/Docs/Doc491.html: Too many open files in system
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at java.nio.file.Files.newBufferedWriter(Files.java:2860)
	at cc.mallet.topics.gui.HtmlBuilder.buildHtml2(HtmlBuilder.java:166)
	at cc.mallet.topics.gui.HtmlBuilder.createHtmlFiles(HtmlBuilder.java:283)
	at cc.mallet.topics.gui.TopicModelingTool.outputCsvFiles(TopicModelingTool.java:1265)
	at cc.mallet.topics.gui.TopicModelingTool.runMallet(TopicModelingTool.java:1181)
	at cc.mallet.topics.gui.TopicModelingTool$TrainButtonListener$1.run(TopicModelingTool.java:468)
```

I've looked through the code, and haven't found an _obvious_ point where files aren't being closed properly. However, the logic of the function that does this work (`buildHtml2` in `HtmlBuilder`) is truly clunky and obviously bug-prone. I'll need to investigate further. This is a hard bug to reproduce since it only happens _sometimes_, even for models with lots of files.

**Comment by senderle** [comment]
It turns out there were lots of places where files weren't being closed. I found them and closed the files.
